---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tendo-config
  namespace: tendo
  labels:
    app.kubernetes.io/name: tendo
    app.kubernetes.io/instance: tendo
data:
  config.yaml: |
    ---
    watchInterval: 5
    watchTargets:
      - secretName: "certificate-a"
        opaqueSecretName: "certificate-a-opaque"
        secretNamespace: "tendo"
        certificateName: "tencent-certificate-a"
        certificateRegion: "ap-singapore"
        certificateResourceTypes:
          - "clb"
          - "tke"

      - secretName: "certificate-b"
        opaqueSecretName: "certificate-b-opaque"
        secretNamespace: "tendo"
        certificateName: "tencent-certificate-b"
        certificateRegion: "ap-singapore"
        certificateResourceTypes:
          - "clb"
          - "tke"