---
apiVersion: v1
kind: Namespace
metadata:
  name: tendo
  labels:
    app.kubernetes.io/name: tendo
    app.kubernetes.io/instance: tendo

---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik