---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tendo
  namespace: tendo
  labels:
    app.kubernetes.io/name: tendo
    app.kubernetes.io/instance: tendo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tendo-secret-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tendo-secret-reader
subjects:
- kind: ServiceAccount
  name: tendo
  namespace: tendo
roleRef:
  kind: ClusterRole
  name: tendo-secret-reader
  apiGroup: rbac.authorization.k8s.io